#!/bin/sh
module="a1303.ko"
device="a1303"
group="vme"
mode="777"


rm -f /dev/${device}

major=`cat /proc/devices | awk "\\$2==\"$device\" {print \\$1}"`

rm -fr /dev/${device}_*

mknod /dev/${device}_0 c $major 0
mknod /dev/${device}_1 c $major 1
mknod /dev/${device}_2 c $major 2
mknod /dev/${device}_3 c $major 3
mknod /dev/${device}_4 c $major 4
mknod /dev/${device}_5 c $major 5
mknod /dev/${device}_6 c $major 6
mknod /dev/${device}_7 c $major 7

chown root   /dev/${device}_*
chgrp $group /dev/${device}_*
chmod $mode  /dev/${device}_*
/sbin/modprobe --ignore-install a1303